unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s

set -g mouse on

# Indexare de la 1 (nu 0)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fcsonline/tmux-thumbs'

# tmux-thumbs config
set -g @thumbs-key F

set-option -g status-position top

# Tema — conditionata per OS
if-shell "uname | grep -q Darwin" "source-file ~/.tmux/themes/catppuccin.conf"
if-shell "uname | grep -q Linux"  "source-file ~/.tmux/themes/tokyo-night.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
